#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "palenight"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "bar"

    buffer_index_type = 4
    windows_index_type = 3

    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode = false

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    automatic_update = true
    # bootstrap_before = "bootstrap_before#init"
    bootstrap_after = "bootstrap_after#init"
    
    default_indent = 4
    expand_tab = true

    project_rooter_patterns = [".git/", "!node_packages/"]

    filetree_direction = "left"

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 30

[[layers]]
name = "tools"

[[layers]]
name = "unite"

[[layers]]
name = "format"

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true
[layer.clang_std]
  cpp = "c17"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"
emmet_leader_key = "<C-e>"
emmet_filetypes = ['html']

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#dart"

[[layers]]
name = "lsp"
filetypes = [
    "c",
    "cpp",
    "go",
    "javascript",
    "typescript"
]

[[layers]]
name = "colorscheme"

